format = """
[î‚¶](#16161D)\
$username\
[î‚°](bg:#1F1F28 fg:#16161D)\
$directory\
[î‚°](fg:#1F1F28 bg:#2A2A37)\
$git_branch\
[î‚°](fg:#2A2A37 bg:#363646)\
$c\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
[î‚°](fg:#363646 bg:#54546D)\
$time\
[î‚° ](fg:#54546D)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like ï„  to save some space
[username]
show_always = true
style_user = "bg:#FF9E3B"
style_root = "bg:#FF9E3B"
format = '[$user ](bg:#16161D)($style)'

[directory]
style = "bg:#1F1F28"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[c]
symbol = "î˜" 
style = "bg:#363646" 
format = '[[ $symbol ($version) ](bg:#363646)]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#2A2A37"
format = '[[ $symbol $branch ](bg:#2A2A37)]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[[($all_status$ahead_behind )](bg:#E46876)]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#363646"
format = '[[ $symbol ](bg:#363646)]($style)'

[haskell]
symbol = "î· "
style = "bg:#363646" 
format = '[[ $symbol ](bg:#363646)]($style)'

[java]
symbol = "î‰– "
style = "bg:#363646" 
format = '[[ $symbol ](bg:#363646)]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#363646" 
format = '[[ $symbol ](bg:#363646)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#363646"
format = '[[ $symbol ](bg:#363646)]($style)'

[rust]
symbol = "ğŸ¦€ "
style = "bg:#363646"
format = '[[ $symbol ](bg:#363646)]($style)'

[python]
symbol = "î˜†"
style = "bg:#363646"
format = '[[ $symbol ](bg:#363646)]($style)'


[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#54546D"
format = '[[ $time ](bg:#54546D)]($style)'
